variable "region" {}
variable "my_project" {}
variable "vpc_cidr" {}
variable "public_subnet_az_01_cidr" {}
variable "public_subnet_az_02_cidr" {}
variable "private_app_subnet_az_01_cidr" {}
variable "private_app_subnet_az_02_cidr" {}
variable "private_data_subnet_az_01_cidr" {}
variable "private_data_subnet_az_02_cidr" {}
variable "my_instance_type" {}
variable "ec2_security_group_id" {}